services:
  ollama:
    image: ollama/ollama:0.11.5 # full GPU usage for llama3.2:3b
    container_name: ollama-test
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./models:/models
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  ollama_data:
