services:
  ollama:
    image: mingzilla/ollama-nomic-embed:1.0.2
    container_name: ollama-service
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
